model_name_or_path: /root/autodl-tmp/gui-grounding-agent/models/Qwen2.5-7B-Instruct
adapter_name_or_path: /root/autodl-tmp/gui-grounding-agent/saves/finqa/qwen25-7b-finqa-full-sft
trust_remote_code: true

stage: dpo
do_train: true
finetuning_type: lora
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target: q_proj,k_proj,v_proj,o_proj
pref_beta: 0.05
pref_loss: sigmoid

dataset_dir: /root/autodl-tmp/gui-grounding-agent/external/LLaMA-Factory/data
dataset: finqa_dpo_clean_balanced
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 2
dataloader_num_workers: 2

output_dir: /root/autodl-tmp/gui-grounding-agent/saves/finqa/qwen25-7b-finqa-dpo-clean-balanced
overwrite_output_dir: true
logging_steps: 10
save_steps: 500
save_total_limit: 2
plot_loss: true

per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
gradient_checkpointing: true

val_size: 0.0
